// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/logged-out": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/settings" | "/logged-out";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/logged-out.tsx": {
    id: "routes/logged-out";
    page: "/logged-out";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/logged-out": typeof import("./app/routes/logged-out.tsx");
};