// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/simulation": {
    params: {};
  };
  "/methodology": {
    params: {};
  };
  "/sources": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/simulation" | "/methodology" | "/sources";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/simulation.tsx": {
    id: "routes/simulation";
    page: "/simulation";
  };
  "routes/methodology.tsx": {
    id: "routes/methodology";
    page: "/methodology";
  };
  "routes/sources.tsx": {
    id: "routes/sources";
    page: "/sources";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/simulation": typeof import("./app/routes/simulation.tsx");
  "routes/methodology": typeof import("./app/routes/methodology.tsx");
  "routes/sources": typeof import("./app/routes/sources.tsx");
};